services:
      redis:
            image: redislabs/redismod
            hostname: redis
            container_name: redis-cont
            ports:
                  - "6379:6379"
            volumes:
                  - redis-data:/data/
            networks:
                  - web-net

      web1:
            restart: on-failure
            build: ./web
            container_name: web1-cont
            hostname: web1

            ports:
                  - "81:5000"
            networks:
                  - web-net
      web2:
            restart: on-failure
            build: ./web
            container_name: web2-cont
            hostname: web2
            ports:
                  - "82:5000"
            networks:
                  - web-net
      nginx:
            build: ./nginx
            container_name: nginx-cont
            ports:
                  - "80:80"
            networks:
                  - web-net
            volumes:
                  - web-data:/usr/share/nginx/html
            depends_on:
                  - web1
                  - web2


volumes:
      redis-data:
      web-data:

networks:
      web-net:
            driver: bridge
